version: "3"

services:
  php:
    build: "./php/"
    networks:
      - web_network
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: "./apache/"
    depends_on:
      - php
      - mysql
    networks:
      # - frontend
      - web_network
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - web_network
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

networks:
  web_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
